image: 10.100.98.41:5000/maao-docker/maao-simple:11.0-maao

variables:
    SERIES_BRANCH: '11.0'
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo

    ODOO_DB_HOST: 10.100.98.41-maao-docker-maao-ci-postgres
    ODOO_DB_USER: odoo
    ODOO_DB_PASSWORD: odoo
    ODOO_ADMIN_PASS: admin

cache:
    paths:
        - "$HOME/.cache/pip"

stages:
    - static-test
    - test
    - translation

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper test flake8 .

pylint:
    stage: static-test
    script:
        - odoo-helper test pylint .

#tests:
#    stage: test
#    services:
#        - 10.100.98.41:5000/maao-docker/maao-ci-postgres
#
#    before_script:
#        - odoo-helper link .
#    script:
#        - odoo-helper --use-unbuffer test --coverage --create-test-db -d .
#        - odoo-helper exec coverage report --fail-under=90
#        - odoo-helper exec coverage html -d html-coverage
#    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
#    artifacts:
#        paths:
#            - html-coverage
#