image: 10.100.98.41:5000/maao-docker/maao-simple:11.0-maao

variables:
    SERIES_BRANCH: '11.0'
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo

    ODOO_DB_HOST: 10.100.98.41-maao-docker-maao-ci-postgres
    ODOO_DB_USER: odoo
    ODOO_DB_PASSWORD: odoo

    ODOO_ADMIN_PASS: admin
    ODOO_PORT: 8069
    ODOO_HOST: localhost

cache:
    paths:
        - "$HOME/.cache/pip"

stages:
    - static-test
    - test
    - translation
    - build

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper test flake8 .

pylint:
    stage: static-test
    script:
        - odoo-helper test pylint .

tests:
    stage: test
    services:
        - 10.100.98.41:5000/maao-docker/maao-ci-postgres

    before_script:
        - odoo-helper link .
    script:
        - echo "odoo_infrastructure_token = qwerty" >> /opt/odoo/conf/odoo.conf
        - echo "server_wide_modules = base,web,odoo_infrastructure_client" >> /opt/odoo/conf/odoo.conf
        - odoo-helper system update dev
        - odoo-helper server start --coverage
        - sleep 5
        - odoo-helper exec python -m unittest run_tests.py
        - odoo-helper stop
        - odoo-helper exec coverage report
        - odoo-helper exec coverage html
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    artifacts:
        paths:
            - html-coverage

.build-docker: &build-docker-definition
    image: docker:stable
    stage: build
    services:
        - name: docker:dind
          command:
            - "--mtu"
            - "1356"
    tags:
        - docker
        - dind
    before_script:
        - docker info
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

        - docker build --rm -t ${CI_REGISTRY_IMAGE}:${RESULT_IMAGE_TAG} --build-arg ODOO_BASE_IMAGE=$ODOO_BASE_IMAGE --build-arg ODOO_BASE_TAG=$ODOO_BASE_TAG .
        - docker push $CI_REGISTRY_IMAGE:${RESULT_IMAGE_TAG}

        - docker logout $CI_REGISTRY

build-client:
    variables:
        ODOO_BASE_IMAGE: "registry.crnd.pro/crnd/docker/odoo-simple"
        ODOO_BASE_TAG: "11.0"
        RESULT_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
    <<: *build-docker-definition

build-client-ci:
    variables:
        ODOO_BASE_IMAGE: "registry.crnd.pro/crnd/docker/odoo-ci"
        ODOO_BASE_TAG: "11.0"
        RESULT_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}-ci"
    <<: *build-docker-definition
