image: registry.crnd.pro/crnd/docker/odoo-ci-x:14.0-simple

variables:
    SERIES_BRANCH: '14.0'
    ODOO_MAX_CRON_THREADS: 0
    ODOO_SERVER_WIDE_MODULES: "base,web,yodoo_client"
    ODOO_EXTRA_CONFIG: "yodoo_token = qwerty"

.pip_cache: &pip_cache_definition
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - "${PIP_CACHE_DIR}"

stages:
    - static-test
    - test
#    - translation
    - build

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper lint flake8 .

pylint:
    stage: static-test
    script:
        - odoo-helper lint pylint .

stylelint:
    stage: static-test
    script:
        - odoo-helper lint style .

#bandit:
    #stage: static-test
    #<<: *pip_cache_definition
    #before_script:
        #- odoo-helper pip install bandit
    #script:
        #- odoo-helper exec bandit -r .

check-versions:
    stage: static-test
    script:
        - odoo-helper ci check-versions-git . origin/$SERIES_BRANCH $CI_COMMIT_SHA
    only:
        - /^14.0-.*$/   # only branches that started with '14.0-'

tests:
    image: registry.crnd.pro/crnd/docker/odoo-ci-x:14.0-ci
    stage: test
    <<: *pip_cache_definition
    before_script:
        - odoo-helper link .
        - odoo-helper pip install odoo-rpc-client requests-toolbelt
    script:
        - odoo-helper server start --coverage
        - sleep 5
        - odoo-helper exec python -m unittest tests
        - odoo-helper stop
        - odoo-helper exec coverage combine
        - odoo-helper exec coverage report
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'

build-docker:
    image: docker:stable
    stage: build
    services:
        - name: docker:dind
          command:
            - "--mtu"
            - "1356"
    variables:
        ODOO_BASE_IMAGE: "registry.crnd.pro/crnd/docker/odoo-simple"
        ODOO_BASE_TAG: "14.0"
        RESULT_IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
    tags:
        - docker
        - dind
    before_script:
        - docker info
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

        - docker build --rm -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --build-arg ODOO_BASE_IMAGE="registry.crnd.pro/crnd/docker/odoo-simple" --build-arg ODOO_BASE_TAG=14.0 .
        - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}

        - docker build --rm -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-ci --build-arg ODOO_BASE_IMAGE="registry.crnd.pro/crnd/docker/odoo-ci" --build-arg ODOO_BASE_TAG=14.0 .
        - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}-ci

        - docker logout $CI_REGISTRY
    only:
        - "14.0"

update-client:
    stage: build
    tags:
        - odoo
        - yodoo_client
        - auto-update
        - v14
    script:
        - sudo -H odoo-helper link -f .
        - sudo -H odoo-helper addons update-list || true
        - sudo -H odoo-helper addons update --dir-r . --skip-errors
    only:
        - "14.0"
