image: registry.crnd.pro/crnd/docker/odoo-ci:11.0

variables:
    SERIES_BRANCH: '11.0'
    ODOO_MAX_CRON_THREADS: 0
    ODOO_SERVER_WIDE_MODULES: "base,web,odoo_infrastructure_client"
    ODOO_EXTRA_CONFIG: "odoo_infrastructure_token = qwerty"

cache:
    paths:
        - "$HOME/.cache/pip"

stages:
    - static-test
    - test
    - translation
    - build

build_env:
    stage: static-test
    script:
        - pwd
        - whoami
        - python --version
        - odoo-helper --version
        - odoo-helper status --tools-versions --ci-tools-versions

flake8:
    stage: static-test
    script:
        - odoo-helper test flake8 .

pylint:
    stage: static-test
    script:
        - odoo-helper test pylint .

tests:
    stage: test
    before_script:
        - odoo-helper link .
    script:
        - odoo-helper server start --coverage
        - sleep 5
        - odoo-helper exec python -m unittest run_tests.py
        - odoo-helper stop
        - odoo-helper exec coverage report
        - odoo-helper exec coverage html
    coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
    artifacts:
        paths:
            - html-coverage

.build-docker: &build-docker-definition
    image: docker:stable
    stage: build
    services:
        - name: docker:dind
          command:
            - "--mtu"
            - "1356"
    tags:
        - docker
        - dind
    before_script:
        - docker info
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

        - docker build --rm -t ${CI_REGISTRY_IMAGE}:${RESULT_IMAGE_TAG} --build-arg ODOO_BASE_IMAGE=$ODOO_BASE_IMAGE --build-arg ODOO_BASE_TAG=$ODOO_BASE_TAG .
        - docker push $CI_REGISTRY_IMAGE:${RESULT_IMAGE_TAG}

        - docker logout $CI_REGISTRY

build-client:
    variables:
        ODOO_BASE_IMAGE: "registry.crnd.pro/crnd/docker/odoo-simple"
        ODOO_BASE_TAG: "11.0"
        RESULT_IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
    <<: *build-docker-definition

build-client-ci:
    variables:
        ODOO_BASE_IMAGE: "registry.crnd.pro/crnd/docker/odoo-ci"
        ODOO_BASE_TAG: "11.0"
        RESULT_IMAGE_TAG: "${CI_COMMIT_REF_NAME}-ci"
    <<: *build-docker-definition
