from . import odoo_infrastructure_auth
from . import odoo_infrastructure_db_statistic
from . import web_settings_dashboard
from . import odoo_infrastructure_client_server_slow_statistic
from . import odoo_infrastructure_client_server_fast_statistic
